**45_Template Matching using OpenCV**

In [43]:
import cv2
import numpy as np

In [44]:
img = cv2.imread(r"C:\Users\hp\Documents\jupyter\OpenCV by WsCube Tech\Images\group.jpg")
img = cv2.resize(img,(500,400))
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

temp = cv2.imread(r"C:\Users\hp\Documents\jupyter\OpenCV by WsCube Tech\Images\c22.jpg")
gray1 = cv2.cvtColor(temp, cv2.COLOR_BGR2GRAY)

#Design a rectangle to find out temp image
# print(gray1.shape)           # (141, 87)

##First find heigh and width

w,h = gray1.shape[::-1]

#For search use template matching
res = cv2.matchTemplate(gray,gray1,cv2.TM_CCOEFF_NORMED)
# print(res)   # Black area points

#Use Threshold value
thr = 0.8


l =np.where(res>=thr)
# print(l)

for i in zip(*l[::-1]):
    cv2.rectangle(img,i,(i[0]+w,i[1]+h),(0,0,255),2)



# cv2.imshow("W",res)
cv2.imshow("Group Image", img)
cv2.imshow("Template Image", temp)
cv2.waitKey(0)
cv2.destroyAllWindows()

###### w,h = gray1.shape[::-1]
w,h

In [21]:
print(l)

(array([  0,   0,   0, ..., 328, 328, 328], dtype=int64), array([  0,   1,   2, ..., 435, 436, 437], dtype=int64))


In [115]:
print(res)

[[0.9560233  0.9564044  0.9568793  ... 0.9640425  0.96466285 0.96521807]
 [0.9559856  0.9564118  0.9568911  ... 0.96407455 0.9647021  0.9651801 ]
 [0.9559763  0.9564084  0.9568908  ... 0.9641831  0.9646816  0.9651388 ]
 ...
 [0.81218743 0.80901825 0.80565214 ... 0.8803291  0.88236815 0.8843359 ]
 [0.81237864 0.80955297 0.8058777  ... 0.8799876  0.88194263 0.88384527]
 [0.81337047 0.8102597  0.8066727  ... 0.87941086 0.8816554  0.88366216]]


In [88]:
r = 0.9020692-0.81391317
r

0.08815603000000005

###### 